# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'EscSXI' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for EscSXI
  
  pod 'NMSSH'

  target 'EscSXI-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'EscSXITests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'EscSXI-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for EscSXI-tvOS

  #target 'EscSXI-tvOSTests' do
  #  inherit! :search_paths
    # Pods for testing
  #end

end
