# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'EscapESXI' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for EscapESXI
  pod 'NMSSH', '~> 2.2.6'

end

target 'EscapESXI-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for EscapESXI-tvOS

  target 'EscapESXI-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
